### ISSUE TITLE
'imagemagick not installed' error

### ISSUE THREAD

**Issue by delta1071** [Wartybix/GNOME-Auto-Accent-Colour#5]
Installed (from Gnome Extensions site and Gnome Extension Manager) in Debian 12 and Ubuntu 24.10. Neither app is functional due its inability to recognize that Imagemagick is in fact installed in both OSes. I have attached a screenshot of the 'Setup' dialog box.
![Screenshot From 2024-11-11 07-06-56](https://github.com/user-attachments/assets/98544875-ceb6-4bb3-99d6-0a7b5805368a)

**Comment by Wartybix** [comment]
Hello, thanks for the bug report.

I'll look into this. I tested this extension on Arch Linux, so maybe there's some incompatibilities with other distros' versions of ImageMagick -- I'll run the extension in some Debian and Ubuntu virtual machines to see what's going on.

The way the extension queries if ImageMagick is installed or not is by checking for the existence of the `magick` command. It could be that on some other distros, I may need to fall back on using the older, deprecated `convert` command.

You mentioned you have ImageMagick installed on both your machines. Can I ask what your terminal outputs when you run `magick`? Is there an output, or does it just return 'command not found'? If running `magick` returns 'command not found', does the same thing happen when you run `convert`? You don't need to pass any arguments to either of these commands.

Finally, can I also ask what happens if you try to set a JPEG or PNG file as your background? I presume you are testing the extension by applying some of the default GNOME backgrounds in the appearance settings. These backgrounds are of SVG and JXL format, and require ImageMagick to parse colour data from them. The extension should still work without error when backgrounds of other file types (e.g. JPG) are applied, even if ImageMagick is not installed.

Thanks for any reply.

**Comment by Wartybix** [comment]
Ah okay, after testing on some VMs, it's as I suspected -- ImageMagick on Debian/Ubuntu still uses the older `convert` command, rather than `magick`. A silly mistake on my part, I should have tested the extension on more distros before I published it.

I'll make the fix to use `convert` as a fallback, and submit a new version to the extensions store.

**Comment by delta1071** [comment]
In case it matters, the terminal output in Ubuntu 24.10 is:

steve@ubuntu:~$ magick
Command 'magick' not found, did you mean:
  command 'magic' from deb magic (8.3.105+ds.1-1.1)
  command 'magics' from deb magics++ (4.15.4-2)
Try: sudo apt install <deb name>

Output from the plain 'convert' command is a list of options, so it seems there's no problem with that command.

Thanks very much your hard work in creating the extension and your quick response to the bug report.

**Comment by Wartybix** [comment]
Thank you for the additional information and kind words 😁.

I decided to revisit this to let you know about some of the changes I've made. The reason why ImageMagick is needed for an SVG or JXL background is to temporarily convert it to a JPG at `~/.cache/auto-accent-colour`, so that ColorThief (the module used for parsing colours from images) can run on it. The extension can apply erroneous accent colours, or crash, if ColorThief runs directly on these file types without converting them.

The versions of ImageMagick on Debian Stable and Ubuntu are quite old compared to on Fedora and Arch Linux, and as such don't supply the `magick` command. Earlier I said that I'll just use the `convert` command as a fallback if `magick` is not found, however I later realised this was also problematic. Older versions of ImageMagick (that still use the `convert` command) don't seem to convert SVGs as well out of the box as newer ones do.

For reference, this is a conversion of an SVG file (left) to a JPG file (right) using ImageMagick 7.1.1 on Arch Linux:
![image](https://github.com/user-attachments/assets/036cafc8-8fe7-4def-9a47-2071d9f75522)

This is the same SVG file (left) converted to a JPG file (right) using ImageMagick 6.9.13 on Ubuntu 24.10:
![image2](https://github.com/user-attachments/assets/ea89dbff-0a52-415c-a1f4-467cb308d164)

ImageMagick 6.9.13 just didn't want to convert this background:
![image3](https://github.com/user-attachments/assets/8d5d01c4-57a5-4c97-994f-9640fb704634)

So I realised there wasn't much point falling back on the old `convert` command when these were the results given anyway. Instead, I have added an alternative optional dependency for users who can't install the newer ImageMagicks -- librsvg. If Debian/Ubuntu users install the `librsvg2-bin` package, SVG backgrounds should be automatically converted with about the same quality as in ImageMagick 7.1.1, and then parsed for accent colours. The downside of librsvg is that it will only convert SVG files, not JXL files. The upside is that I'm not sure many people actually use JXL files anyway -- I only knew about JXL files because upstream GNOME use some of them for their default backgrounds. But Ubuntu uses its own backgrounds (mostly JPGs and PNGs), and doesn't seem to have JXL file support out of the box. So I don't think Ubuntu users will be missing out on much. And users already running GNOME 47 on Debian can probably just install [ImageMagick 7.1.1 from the unstable branch](https://packages.debian.org/sid/any/imagemagick-7.q16) for the extension to work with JXL backgrounds.

I've also provided info about the alternative converter in the 'Setup' preferences page. I have now clarified that the installation of *ImageMagick v7+* is what's being queried in the 'Setup' page, not just *any* ImageMagick. I've also clarified that these dependencies are **optional**, and aren't required if the user doesn't plan on applying SVG or JXL backgrounds.
![Screenshot From 2024-11-12 01-56-06](https://github.com/user-attachments/assets/fd27f656-5364-43ab-8345-c672866ddede)

These changes will appear in the extension's next version update.
